version: '3'

services:
  db:
    image: postgres
    hostname: db
    container_name: db
    ports:
      - 5432:5432
    networks:
      - djangonetwork
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
      dockerfile: config/app/Dockerfile
    hostname: "app"
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - djangonetwork

  nginx:
    image: "nginx"
    hostname: "nginx"
    ports:
      - "8000:8000"
    volumes:
      # - ./config/nginx:/etc/nginx/
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - djangonetwork
      - default

networks:
    djangonetwork:
      driver: bridge
