version: '3'

services:
  db:
    image: postgres
    hostname: db
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  app:
    image: myproject:latest
    hostname: app
    build:
      context: .
      dockerfile: ./config/app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/staticfiles:/static
    depends_on:
      - app
